name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Alsa deps
      run: sudo apt-get install -y libasound2-dev portaudio19-dev build-essential libpulse-dev libdbus-1-dev
    - name: LibU deps
      run: sudo apt install -y libudev-dev pkg-config
    - name: Build
      run: cargo build --release --verbose
    - name: Archive binary
      uses: actions/upload-artifact@v4
      with:
          name: bevy-universe
          path: target/release/bevy-universe
